/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package piiiuascuaca.view;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import piiiuascuaca.model.Cuaca;

/**
 *
 * @author imanmuliawan
 */
public class inputCuaca extends javax.swing.JFrame {
    public String id_cuaca;
    public String tanggal;
    public String nama_kota;
    public String suhu_normal;
    public String suhu_maks;
    public String suhu_min;
    public String kecepatan_angin;
    public String kelembapan;
    public String tekanan_udara;
    /**
     * Creates new form inputCuaca
     */
    public inputCuaca() {
        initComponents();
    }
    
    public inputCuaca(String id) throws SQLException{
        initComponents();
        id_cuaca = id;
        if(!id_cuaca.isEmpty()){
            Statement st = koneksi.getConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM t_cuaca WHERE id = '"+ id_cuaca +"'");
            while(rs.next()){
                tanggal = rs.getString("date");
                txtNamaKota.setText(rs.getString("nama_kota"));
                txtSuhu.setText(rs.getString("suhu"));
                txtSuhuMaks.setText(rs.getString("suhu_maks"));
                txtSuhuMin.setText(rs.getString("suhu_min"));
                txtKecepatanAngin.setText(rs.getString("kecepatan_angin"));
                txtKelembapan.setText(rs.getString("kelembapan"));
                txtTekananUdara.setText(rs.getString("tekanan_udara"));
            }
        }
        tanggal = (tanggal.substring(8, 10)) + "-" + tanggal.substring(5, 7) + "-"+ tanggal.substring(0, 4);
        txtTanggal.setText(tanggal.substring(0, 10));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtNamaKota = new javax.swing.JTextField();
        txtSuhu = new javax.swing.JTextField();
        txtSuhuMaks = new javax.swing.JTextField();
        txtSuhuMin = new javax.swing.JTextField();
        txtKelembapan = new javax.swing.JTextField();
        txtKecepatanAngin = new javax.swing.JTextField();
        txtTekananUdara = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("INPUT DATA CUACA");

        jLabel2.setText("Tanggal");

        jLabel3.setText("Nama Kota");

        jLabel4.setText("Suhu");

        jLabel5.setText("Suhu Maksimal");

        jLabel6.setText("Suhu Minimal");

        jLabel7.setText("Kelembapan");

        jLabel8.setText("Kecepatan Angin");

        jLabel9.setText("Tekanan Udara");

        txtTanggal.setName("txtTanggal"); // NOI18N
        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        txtNamaKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKotaActionPerformed(evt);
            }
        });

        txtKelembapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKelembapanActionPerformed(evt);
            }
        });

        txtTekananUdara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTekananUdaraActionPerformed(evt);
            }
        });

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTanggal)
                                .addComponent(txtNamaKota)
                                .addComponent(txtSuhu)
                                .addComponent(txtSuhuMaks)
                                .addComponent(txtSuhuMin)
                                .addComponent(txtKelembapan)
                                .addComponent(txtKecepatanAngin)
                                .addComponent(txtTekananUdara, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSuhuMaks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSuhuMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(txtKelembapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(txtKecepatanAngin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(txtTekananUdara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKelembapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelembapanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelembapanActionPerformed

    private void txtNamaKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKotaActionPerformed

    private void txtTekananUdaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTekananUdaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTekananUdaraActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtTanggal.getText().isEmpty()){
            this.dispose();
        }else{
        String newDateString = "";
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date startDate;
        try {
            startDate = dateFormat.parse(txtTanggal.getText());
            DateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM-dd");
            newDateString = dateFormat2.format(startDate);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        try{
            if(id_cuaca.isEmpty()){
                PreparedStatement st = koneksi.getConnection().prepareStatement(""
                        + "INSERT INTO t_cuaca "
                        + " (`date`, `nama_kota`, `suhu`, `suhu_maks`, `suhu_min`, "
                        + "`kecepatan_angin`, `kelembapan`, `tekanan_udara`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)");
                    st.setString(1, newDateString + " 00:00:00");
                    st.setString(2, txtNamaKota.getText());
                    st.setString(3, txtSuhu.getText());
                    st.setString(4, txtSuhuMaks.getText());
                    st.setString(5, txtSuhuMin.getText());
                    st.setString(6, txtKecepatanAngin.getText());
                    st.setString(7, txtKelembapan.getText());
                    st.setString(8, txtTekananUdara.getText());
                    System.out.println(st);
                    st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil di Input");
                
                txtTanggal.setText("");
                txtNamaKota.setText("");
                txtSuhu.setText("");
                txtSuhuMaks.setText("");
                txtSuhuMin.setText("");
                txtKecepatanAngin.setText("");
                txtKelembapan.setText("");
                txtTekananUdara.setText("");
            }else{
                PreparedStatement st = koneksi.getConnection().prepareStatement(""
                        + "UPDATE t_cuaca "
                        + "SET `date` = ?, `nama_kota` = ? , `suhu` = ?, `suhu_maks` = ?, `suhu_min` = ?,"
                        + "`kecepatan_angin`= ?, `kelembapan`= ?, `tekanan_udara`= ? WHERE `id` = ?");
                    st.setString(1, newDateString + " 00:00:00");
                    st.setString(2, txtNamaKota.getText());
                    st.setString(3, txtSuhu.getText());
                    st.setString(4, txtSuhuMaks.getText());
                    st.setString(5, txtSuhuMin.getText());
                    st.setString(6, txtKecepatanAngin.getText());
                    st.setString(7, txtKelembapan.getText());
                    st.setString(8, txtTekananUdara.getText());
                    st.setString(9, id_cuaca);
                    
                    st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
            }
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void setId(String id_cuaca){
        this.id_cuaca = id_cuaca;
    }
    
    public String getId(){
        return id_cuaca;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputCuaca().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtKecepatanAngin;
    private javax.swing.JTextField txtKelembapan;
    private javax.swing.JTextField txtNamaKota;
    private javax.swing.JTextField txtSuhu;
    private javax.swing.JTextField txtSuhuMaks;
    private javax.swing.JTextField txtSuhuMin;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTekananUdara;
    // End of variables declaration//GEN-END:variables
}

